View: override Zend/View/Abstract's dynamic property management
Store dynamic properties in an array.
W/o this the login page, if on PHP 8.2, says:

Deprecated: Creation of dynamic property Icinga\Web\View::$defaultTitle is deprecated in /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php on line 305
Deprecated: Creation of dynamic property Icinga\Web\View::$compact is deprecated in /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php on line 305
Deprecated: Creation of dynamic property Icinga\Web\View::$tabs is deprecated in /usr/share/icingaweb2/library/vendor/Zend/View/Abstract.php on line 305

W/o View#getVars() the login page says:

Fatal error: Uncaught ErrorException: Uncaught ErrorException: Undefined variable $hideControls in /usr/share/icingaweb2/application/views/scripts/error/error.phtml:1